# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./MathLibrary/Bounding/BoundingBox.h \
    ./MathLibrary/functions.h \
    ./Utility/ColorMap.h \
    ./GraphicsLibrary/Sampling/EdgeSampler.h \
    ./GL/GLee.h \
    ./Utility/Graph.h \
    ./Utility/HashTable.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_.h \
    ./GraphicsLibrary/Basic/Line.h \
    ./Utility/Macros.h \
    ./Utility/NoiseGen.h \
    ./GraphicsLibrary/SpacePartition/Octree.h \
    ./GraphicsLibrary/Basic/Plane.h \
    ./GraphicsLibrary/Basic/PolygonArea.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Quadric.h \
    ./GraphicsLibrary/Sampling/RegularRecursive.h \
    ./GraphicsLibrary/Sampling/Sampler.h \
    ./Utility/SimpleDraw.h \
    ./Utility/Sleeper.h \
    ./GraphicsLibrary/Sampling/SliceSampling.h \
    ./GraphicsLibrary/Sampling/SpherePackSampling.h \
    ./Utility/Stats.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Surface_mesh.h \
    ./GraphicsLibrary/Basic/Triangle.h \
    ./GL/VBO/VBO.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Vector.h \
    ./GraphicsLibrary/Voxel/Voxel.h \
    ./GraphicsLibrary/Sampling/VoxelSampling.h \
    ./GraphicsLibrary/Voxel/Voxeler.h \
    ./GUI/global.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/properties.h \
    ./GUI/Tools/DrawLinePanel.h \
    ./GUI/MeshBrowser/MeshBrowserWidget.h \
    ./GUI/Tools/MeshInfoPanel.h \
    ./GUI/QMeshDoc.h \
    ./GraphicsLibrary/Mesh/QSegMesh.h \
    ./GraphicsLibrary/Mesh/QSurfaceMesh.h \
    ./GUI/MeshBrowser/QuickMesh.h \
    ./GUI/MeshBrowser/QuickMeshViewer.h \
    ./GUI/Scene.h \
    ./GUI/Tools/TransformationPanel.h \
    ./GUI/Workspace.h \
    ./MathLibrary/d_delaunay.h \
    ./MathLibrary/d_edge.h \
    ./MathLibrary/d_numeric.h \
    ./MathLibrary/d_vector2.h \
    ./MathLibrary/d_triangle.h
SOURCES += ./GUI/Tools/DrawLinePanel.cpp \
    ./MathLibrary/Bounding/BoundingBox.cpp \
    ./MathLibrary/functions.cpp \
    ./Utility/ColorMap.cpp \
    ./GL/GLee.c \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_obj.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_off.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_stl.cpp \
    ./GraphicsLibrary/Basic/Line.cpp \
    ./GUI/MeshBrowser/MeshBrowserWidget.cpp \
    ./GUI/Tools/MeshInfoPanel.cpp \
    ./GraphicsLibrary/SpacePartition/Octree.cpp \
    ./GraphicsLibrary/Basic/Plane.cpp \
    ./GUI/QMeshDoc.cpp \
    ./GraphicsLibrary/Mesh/QSegMesh.cpp \
    ./GraphicsLibrary/Mesh/QSurfaceMesh.cpp \
    ./GUI/MeshBrowser/QuickMeshViewer.cpp \
    ./GraphicsLibrary/Sampling/Sampler.cpp \
    ./GUI/Scene.cpp \
    ./Utility/SimpleDraw.cpp \
    ./Utility/Stats.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Surface_mesh.cpp \
    ./GUI/Tools/TransformationPanel.cpp \
    ./GraphicsLibrary/Basic/Triangle.cpp \
    ./GL/VBO/VBO.cpp \
    ./GraphicsLibrary/Voxel/Voxeler.cpp \
    ./GUI/Workspace.cpp \
    ./GUI/global.cpp \
    ./GraphicsLibrary/SpacePartition/kdtree.cpp \
    ./GUI/main.cpp
FORMS += ./GUI/MeshBrowser/MeshBrowserForm.ui \
    ./GUI/Tools/DrawLineWidget.ui \
    ./GUI/Tools/MeshInfo.ui \
    ./GUI/Tools/RotationWidget.ui \
    ./GUI/Workspace.ui
RESOURCES += Workspace.qrc
